#ifndef _ALTERA_HPS_SOC_SYSTEM_H_
#define _ALTERA_HPS_SOC_SYSTEM_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'hw/quartus/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'sdram_controller_0', class 'altera_avalon_new_sdram_controller'
 * The macros are prefixed with 'SDRAM_CONTROLLER_0_'.
 * The prefix is the slave descriptor.
 */
#define SDRAM_CONTROLLER_0_COMPONENT_TYPE altera_avalon_new_sdram_controller
#define SDRAM_CONTROLLER_0_COMPONENT_NAME sdram_controller_0
#define SDRAM_CONTROLLER_0_BASE 0x0
#define SDRAM_CONTROLLER_0_SPAN 67108864
#define SDRAM_CONTROLLER_0_END 0x3ffffff
#define SDRAM_CONTROLLER_0_CAS_LATENCY 3
#define SDRAM_CONTROLLER_0_CONTENTS_INFO 
#define SDRAM_CONTROLLER_0_INIT_NOP_DELAY 0.0
#define SDRAM_CONTROLLER_0_INIT_REFRESH_COMMANDS 2
#define SDRAM_CONTROLLER_0_IS_INITIALIZED 1
#define SDRAM_CONTROLLER_0_POWERUP_DELAY 100.0
#define SDRAM_CONTROLLER_0_REFRESH_PERIOD 7.8125
#define SDRAM_CONTROLLER_0_REGISTER_DATA_IN 1
#define SDRAM_CONTROLLER_0_SDRAM_ADDR_WIDTH 25
#define SDRAM_CONTROLLER_0_SDRAM_BANK_WIDTH 2
#define SDRAM_CONTROLLER_0_SDRAM_COL_WIDTH 10
#define SDRAM_CONTROLLER_0_SDRAM_DATA_WIDTH 16
#define SDRAM_CONTROLLER_0_SDRAM_NUM_BANKS 4
#define SDRAM_CONTROLLER_0_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_CONTROLLER_0_SDRAM_ROW_WIDTH 13
#define SDRAM_CONTROLLER_0_SHARED_DATA 0
#define SDRAM_CONTROLLER_0_SIM_MODEL_BASE 0
#define SDRAM_CONTROLLER_0_STARVATION_INDICATOR 0
#define SDRAM_CONTROLLER_0_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_CONTROLLER_0_T_AC 5.4
#define SDRAM_CONTROLLER_0_T_MRD 3
#define SDRAM_CONTROLLER_0_T_RCD 15.0
#define SDRAM_CONTROLLER_0_T_RFC 70.0
#define SDRAM_CONTROLLER_0_T_RP 15.0
#define SDRAM_CONTROLLER_0_T_WR 14.0
#define SDRAM_CONTROLLER_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define SDRAM_CONTROLLER_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define SDRAM_CONTROLLER_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 16

/*
 * Macros for device 'Encoder_0', class 'Encoder'
 * The macros are prefixed with 'ENCODER_0_'.
 * The prefix is the slave descriptor.
 */
#define ENCODER_0_COMPONENT_TYPE Encoder
#define ENCODER_0_COMPONENT_NAME Encoder_0
#define ENCODER_0_BASE 0x4000000
#define ENCODER_0_SPAN 32
#define ENCODER_0_END 0x400001f

/*
 * Macros for device 'led_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_COMPONENT_NAME led_pio
#define LED_PIO_BASE 0x4000020
#define LED_PIO_SPAN 32
#define LED_PIO_END 0x400003f
#define LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 1
#define LED_PIO_CAPTURE 0
#define LED_PIO_DATA_WIDTH 10
#define LED_PIO_DO_TEST_BENCH_WIRING 0
#define LED_PIO_DRIVEN_SIM_VALUE 0
#define LED_PIO_EDGE_TYPE NONE
#define LED_PIO_FREQ 50000000
#define LED_PIO_HAS_IN 0
#define LED_PIO_HAS_OUT 1
#define LED_PIO_HAS_TRI 0
#define LED_PIO_IRQ_TYPE NONE
#define LED_PIO_RESET_VALUE 0

/*
 * Macros for device 'gpio_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'GPIO_PIO_'.
 * The prefix is the slave descriptor.
 */
#define GPIO_PIO_COMPONENT_TYPE altera_avalon_pio
#define GPIO_PIO_COMPONENT_NAME gpio_pio
#define GPIO_PIO_BASE 0x4000040
#define GPIO_PIO_SPAN 32
#define GPIO_PIO_END 0x400005f
#define GPIO_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define GPIO_PIO_BIT_MODIFYING_OUTPUT_REGISTER 1
#define GPIO_PIO_CAPTURE 0
#define GPIO_PIO_DATA_WIDTH 8
#define GPIO_PIO_DO_TEST_BENCH_WIRING 0
#define GPIO_PIO_DRIVEN_SIM_VALUE 0
#define GPIO_PIO_EDGE_TYPE NONE
#define GPIO_PIO_FREQ 50000000
#define GPIO_PIO_HAS_IN 0
#define GPIO_PIO_HAS_OUT 1
#define GPIO_PIO_HAS_TRI 0
#define GPIO_PIO_IRQ_TYPE NONE
#define GPIO_PIO_RESET_VALUE 0


#endif /* _ALTERA_HPS_SOC_SYSTEM_H_ */
